// Package productive provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package productive

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ResourceBookingApprovalStatus.
const (
	ResourceBookingApprovalStatusN1 ResourceBookingApprovalStatus = 1
	ResourceBookingApprovalStatusN2 ResourceBookingApprovalStatus = 2
	ResourceBookingApprovalStatusN3 ResourceBookingApprovalStatus = 3
	ResourceBookingApprovalStatusN5 ResourceBookingApprovalStatus = 5
)

// Defines values for ResourceBookingBillingTypeId.
const (
	ResourceBookingBillingTypeIdN1 ResourceBookingBillingTypeId = 1
	ResourceBookingBillingTypeIdN2 ResourceBookingBillingTypeId = 2
	ResourceBookingBillingTypeIdN3 ResourceBookingBillingTypeId = 3
	ResourceBookingBillingTypeIdN4 ResourceBookingBillingTypeId = 4
)

// Defines values for ResourceBookingBookingMethodId.
const (
	ResourceBookingBookingMethodIdN1 ResourceBookingBookingMethodId = 1
	ResourceBookingBookingMethodIdN2 ResourceBookingBookingMethodId = 2
	ResourceBookingBookingMethodIdN3 ResourceBookingBookingMethodId = 3
)

// Defines values for ResourceBookingPersonType.
const (
	ResourceBookingPersonTypeN1 ResourceBookingPersonType = 1
	ResourceBookingPersonTypeN2 ResourceBookingPersonType = 2
	ResourceBookingPersonTypeN3 ResourceBookingPersonType = 3
	ResourceBookingPersonTypeN4 ResourceBookingPersonType = 4
)

// Defines values for ResourceBookingProjectType.
const (
	ResourceBookingProjectTypeN1 ResourceBookingProjectType = 1
	ResourceBookingProjectTypeN2 ResourceBookingProjectType = 2
)

// Defines values for ResourceBookingStageType.
const (
	ResourceBookingStageTypeN1 ResourceBookingStageType = 1
	ResourceBookingStageTypeN2 ResourceBookingStageType = 2
)

// Defines values for ResourceEventAbsenceType.
const (
	RemoteWork ResourceEventAbsenceType = "remote_work"
	TimeOff    ResourceEventAbsenceType = "time_off"
)

// Defines values for ResourceEventEventTypeId.
const (
	ResourceEventEventTypeIdN1 ResourceEventEventTypeId = 1
	ResourceEventEventTypeIdN2 ResourceEventEventTypeId = 2
)

// Defines values for ResourceEventLimitationType.
const (
	ResourceEventLimitationTypeN2 ResourceEventLimitationType = 2
	ResourceEventLimitationTypeN3 ResourceEventLimitationType = 3
	ResourceEventLimitationTypeN4 ResourceEventLimitationType = 4
)

// Defines values for ResourceEventLimitationTypeId.
const (
	ResourceEventLimitationTypeIdN2 ResourceEventLimitationTypeId = 2
	ResourceEventLimitationTypeIdN3 ResourceEventLimitationTypeId = 3
	ResourceEventLimitationTypeIdN4 ResourceEventLimitationTypeId = 4
)

// Defines values for ResourceEventStatus.
const (
	ResourceEventStatusN1 ResourceEventStatus = 1
	ResourceEventStatusN2 ResourceEventStatus = 2
)

// Defines values for ResourcePersonHrmTypeId.
const (
	ResourcePersonHrmTypeIdN1 ResourcePersonHrmTypeId = 1
	ResourcePersonHrmTypeIdN2 ResourcePersonHrmTypeId = 2
)

// Defines values for ResourcePersonOffboardingStatus.
const (
	ResourcePersonOffboardingStatusCompleted    ResourcePersonOffboardingStatus = "completed"
	ResourcePersonOffboardingStatusFailed       ResourcePersonOffboardingStatus = "failed"
	ResourcePersonOffboardingStatusInProgress   ResourcePersonOffboardingStatus = "in_progress"
	ResourcePersonOffboardingStatusNotInitiated ResourcePersonOffboardingStatus = "not_initiated"
)

// Defines values for ResourcePersonStatus.
const (
	ResourcePersonStatusN1 ResourcePersonStatus = 1
	ResourcePersonStatusN2 ResourcePersonStatus = 2
)

// Defines values for ResourceProjectDuplicationStatus.
const (
	ResourceProjectDuplicationStatusFailed     ResourceProjectDuplicationStatus = "failed"
	ResourceProjectDuplicationStatusIdle       ResourceProjectDuplicationStatus = "idle"
	ResourceProjectDuplicationStatusInProgress ResourceProjectDuplicationStatus = "in_progress"
)

// Defines values for ResourceProjectProjectType.
const (
	ResourceProjectProjectTypeN1 ResourceProjectProjectType = 1
	ResourceProjectProjectTypeN2 ResourceProjectProjectType = 2
)

// Defines values for ResourceProjectProjectTypeId.
const (
	ResourceProjectProjectTypeIdN1 ResourceProjectProjectTypeId = 1
	ResourceProjectProjectTypeIdN2 ResourceProjectProjectTypeId = 2
)

// Defines values for ResourceProjectStatus.
const (
	ResourceProjectStatusN1 ResourceProjectStatus = 1
	ResourceProjectStatusN2 ResourceProjectStatus = 2
)

// Defines values for ResourceServiceBillingType.
const (
	ResourceServiceBillingTypeN1 ResourceServiceBillingType = 1
	ResourceServiceBillingTypeN2 ResourceServiceBillingType = 2
	ResourceServiceBillingTypeN3 ResourceServiceBillingType = 3
	ResourceServiceBillingTypeN4 ResourceServiceBillingType = 4
)

// Defines values for ResourceServiceBillingTypeId.
const (
	ResourceServiceBillingTypeIdN1 ResourceServiceBillingTypeId = 1
	ResourceServiceBillingTypeIdN2 ResourceServiceBillingTypeId = 2
	ResourceServiceBillingTypeIdN3 ResourceServiceBillingTypeId = 3
	ResourceServiceBillingTypeIdN4 ResourceServiceBillingTypeId = 4
)

// Defines values for ResourceServiceBudgetStatus.
const (
	ResourceServiceBudgetStatusN1 ResourceServiceBudgetStatus = 1
	ResourceServiceBudgetStatusN2 ResourceServiceBudgetStatus = 2
)

// Defines values for ResourceServiceLimitationType.
const (
	BudgetFullyUsed    ResourceServiceLimitationType = "budget_fully_used"
	EstimateLimitation ResourceServiceLimitationType = "estimate_limitation"
	NoLimitation       ResourceServiceLimitationType = "no_limitation"
	QuantityLimitation ResourceServiceLimitationType = "quantity_limitation"
)

// Defines values for ResourceServiceProjectType.
const (
	ResourceServiceProjectTypeN1 ResourceServiceProjectType = 1
	ResourceServiceProjectTypeN2 ResourceServiceProjectType = 2
)

// Defines values for ResourceServiceRevampedUnit.
const (
	ResourceServiceRevampedUnitN1 ResourceServiceRevampedUnit = 1
	ResourceServiceRevampedUnitN2 ResourceServiceRevampedUnit = 2
	ResourceServiceRevampedUnitN3 ResourceServiceRevampedUnit = 3
)

// Defines values for ResourceServiceSalesStatusId.
const (
	ResourceServiceSalesStatusIdN1 ResourceServiceSalesStatusId = 1
	ResourceServiceSalesStatusIdN2 ResourceServiceSalesStatusId = 2
	ResourceServiceSalesStatusIdN3 ResourceServiceSalesStatusId = 3
	ResourceServiceSalesStatusIdN4 ResourceServiceSalesStatusId = 4
)

// Defines values for ResourceServiceStageStatusId.
const (
	ResourceServiceStageStatusIdN1 ResourceServiceStageStatusId = 1
	ResourceServiceStageStatusIdN2 ResourceServiceStageStatusId = 2
	ResourceServiceStageStatusIdN3 ResourceServiceStageStatusId = 3
	ResourceServiceStageStatusIdN4 ResourceServiceStageStatusId = 4
)

// Defines values for ResourceServiceStageType.
const (
	ResourceServiceStageTypeN1 ResourceServiceStageType = 1
	ResourceServiceStageTypeN2 ResourceServiceStageType = 2
)

// Defines values for ResourceServiceUnit.
const (
	ResourceServiceUnitN1 ResourceServiceUnit = 1
	ResourceServiceUnitN2 ResourceServiceUnit = 2
	ResourceServiceUnitN3 ResourceServiceUnit = 3
)

// Defines values for ResourceServiceUnitId.
const (
	ResourceServiceUnitIdN1 ResourceServiceUnitId = 1
	ResourceServiceUnitIdN2 ResourceServiceUnitId = 2
	ResourceServiceUnitIdN3 ResourceServiceUnitId = 3
)

// Defines values for ResourceTimeEntryBillingTypeId.
const (
	ResourceTimeEntryBillingTypeIdN1 ResourceTimeEntryBillingTypeId = 1
	ResourceTimeEntryBillingTypeIdN2 ResourceTimeEntryBillingTypeId = 2
	ResourceTimeEntryBillingTypeIdN3 ResourceTimeEntryBillingTypeId = 3
	ResourceTimeEntryBillingTypeIdN4 ResourceTimeEntryBillingTypeId = 4
)

// Defines values for ResourceTimeEntryInvoicingStatus.
const (
	ResourceTimeEntryInvoicingStatusN1 ResourceTimeEntryInvoicingStatus = 1
	ResourceTimeEntryInvoicingStatusN2 ResourceTimeEntryInvoicingStatus = 2
	ResourceTimeEntryInvoicingStatusN3 ResourceTimeEntryInvoicingStatus = 3
)

// Defines values for ResourceTimeEntryStageType.
const (
	ResourceTimeEntryStageTypeN1 ResourceTimeEntryStageType = 1
	ResourceTimeEntryStageTypeN2 ResourceTimeEntryStageType = 2
)

// Defines values for ResourceTimeEntryStatus.
const (
	ResourceTimeEntryStatusN1 ResourceTimeEntryStatus = 1
	ResourceTimeEntryStatusN2 ResourceTimeEntryStatus = 2
	ResourceTimeEntryStatusN3 ResourceTimeEntryStatus = 3
	ResourceTimeEntryStatusN4 ResourceTimeEntryStatus = 4
	ResourceTimeEntryStatusN5 ResourceTimeEntryStatus = 5
	ResourceTimeEntryStatusN6 ResourceTimeEntryStatus = 6
)

// Defines values for ResourceTimeEntryTrackMethodId.
const (
	ResourceTimeEntryTrackMethodIdN1 ResourceTimeEntryTrackMethodId = 1
	ResourceTimeEntryTrackMethodIdN2 ResourceTimeEntryTrackMethodId = 2
	ResourceTimeEntryTrackMethodIdN3 ResourceTimeEntryTrackMethodId = 3
	ResourceTimeEntryTrackMethodIdN4 ResourceTimeEntryTrackMethodId = 4
	ResourceTimeEntryTrackMethodIdN5 ResourceTimeEntryTrackMethodId = 5
	ResourceTimeEntryTrackMethodIdN6 ResourceTimeEntryTrackMethodId = 6
)

// Defines values for ResourceTimeEntryUnitId.
const (
	N1 ResourceTimeEntryUnitId = 1
	N2 ResourceTimeEntryUnitId = 2
	N3 ResourceTimeEntryUnitId = 3
)

// Meta Pagination and response metadata returned with every collection endpoint.
type Meta struct {
	// CurrentPage The current page number in this paginated response (1-based).
	CurrentPage *int `json:"current_page,omitempty"`

	// MaxPageSize Maximum number of records allowed per page for this endpoint.
	MaxPageSize *int `json:"max_page_size,omitempty"`

	// OrganizationFeatures Feature flags and capabilities enabled for the current organization, used for UI rendering.
	OrganizationFeatures *map[string]interface{} `json:"organization_features,omitempty"`

	// PageSize Number of records returned per page in this response.
	PageSize *int `json:"page_size,omitempty"`

	// Settings Organization or user settings relevant to this resource's display.
	Settings *map[string]interface{} `json:"settings,omitempty"`

	// TotalCount Total number of records matching the current query across all pages.
	TotalCount *int `json:"total_count,omitempty"`

	// TotalPages Total number of pages available for the current query and page size.
	TotalPages *int `json:"total_pages,omitempty"`
}

// ResourceBooking A booking represents planned work or an absence scheduled for a person, linked to a service or absence category.
type ResourceBooking struct {
	// After Internal field used for date-range filtering.
	After *openapi_types.Date `json:"after,omitempty"`

	// ApprovalStatus Whether the booking has been approved. Reflects the overall approval_status.
	ApprovalStatus *ResourceBookingApprovalStatus `json:"approval_status,omitempty"`

	// ApprovalStatuses Per-approver approval status records for this booking.
	ApprovalStatuses *interface{} `json:"approval_statuses,omitempty"`

	// Approved Indicates whether the booking has been approved.
	Approved *interface{} `json:"approved,omitempty"`

	// ApprovedAt Timestamp when the booking was approved, or null if not yet approved.
	ApprovedAt *time.Time `json:"approved_at,omitempty"`

	// Approver The person who approved this booking.
	Approver *interface{} `json:"approver,omitempty"`

	// ApproverId The ID of the person who approved this booking.
	ApproverId *int `json:"approver_id,omitempty"`

	// AttachmentIds Array of IDs of files attached to this booking.
	AttachmentIds *interface{} `json:"attachment_ids,omitempty"`

	// Attachments Files attached to this booking.
	Attachments *interface{} `json:"attachments,omitempty"`

	// Autotracking When true, time entries are automatically tracked against this booking.
	Autotracking *bool `json:"autotracking,omitempty"`

	// Before Internal field used for date-range filtering.
	Before *openapi_types.Date `json:"before,omitempty"`

	// BillingTypeId ID of the billing type of the associated service.
	BillingTypeId *ResourceBookingBillingTypeId `json:"billing_type_id,omitempty"`

	// BookingMethodId ID of the booking method used to create this booking (e.g. hours per day, percentage, total hours).
	BookingMethodId *ResourceBookingBookingMethodId `json:"booking_method_id,omitempty"`

	// BookingType Whether this is a project booking or an absence booking.
	BookingType *string `json:"booking_type,omitempty"`

	// BudgetId ID of the budget (deal) associated with the booking's service.
	BudgetId *int `json:"budget_id,omitempty"`

	// Canceled Whether this booking has been canceled.
	Canceled *bool `json:"canceled,omitempty"`

	// CanceledAt Date when the booking was canceled.
	CanceledAt *time.Time `json:"canceled_at,omitempty"`

	// Canceler The person who canceled this booking.
	Canceler *interface{} `json:"canceler,omitempty"`

	// CompanyId ID of the client company associated with this booking.
	CompanyId *int `json:"company_id,omitempty"`

	// CreatedAt Date when the booking was created.
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Creator The person who created this booking.
	Creator *interface{} `json:"creator,omitempty"`

	// CustomFieldAttachments File attachments linked via custom fields on this booking.
	CustomFieldAttachments *interface{} `json:"custom_field_attachments,omitempty"`

	// CustomFieldPeople People linked via custom fields on this booking.
	CustomFieldPeople *interface{} `json:"custom_field_people,omitempty"`

	// CustomFields Custom field values for this booking.
	CustomFields *map[string]interface{} `json:"custom_fields,omitempty"`

	// Draft Whether the booking is tentative (draft) or confirmed.
	Draft *bool `json:"draft,omitempty"`

	// EndedOn Booking end date.
	EndedOn *openapi_types.Date `json:"ended_on,omitempty"`

	// Event The absence event category (e.g. vacation, sick leave) for absence bookings.
	Event *interface{} `json:"event,omitempty"`

	// EventId ID of the absence event category for this booking.
	EventId *int `json:"event_id,omitempty"`

	// ExternalId External identifier for integration with third-party systems.
	ExternalId *string `json:"external_id,omitempty"`

	// Hours Scheduled hours per day for this booking.
	Hours *int `json:"hours,omitempty"`

	// Id Unique identifier of the booking.
	Id *int `json:"id,omitempty"`

	// LastActivityAt Timestamp of the last activity recorded on this booking.
	LastActivityAt *time.Time `json:"last_activity_at,omitempty"`

	// Note An optional note or description for this booking.
	Note *string `json:"note,omitempty"`

	// Organization The organization this booking belongs to.
	Organization *interface{} `json:"organization,omitempty"`

	// Origin The booking origin (e.g. the resource request that generated this booking).
	Origin *interface{} `json:"origin,omitempty"`

	// OriginId The ID of the origin record (e.g. resource request) that created this booking.
	OriginId *int `json:"origin_id,omitempty"`

	// PeopleCustomFields Custom field values defined on the assigned person.
	PeopleCustomFields *string `json:"people_custom_fields,omitempty"`

	// Percentage Scheduled time as a percentage of the person's daily capacity.
	Percentage *int `json:"percentage,omitempty"`

	// Person The person assigned to this booking.
	Person *interface{} `json:"person,omitempty"`

	// PersonId ID of the person assigned to this booking.
	PersonId *int `json:"person_id,omitempty"`

	// PersonSubsidiaryId ID of the subsidiary the assigned person belongs to.
	PersonSubsidiaryId *int `json:"person_subsidiary_id,omitempty"`

	// PersonType Type of the assigned person (e.g. employee, contractor, placeholder).
	PersonType *ResourceBookingPersonType `json:"person_type,omitempty"`

	// ProjectId ID of the project this booking relates to.
	ProjectId *int `json:"project_id,omitempty"`

	// ProjectType Type of the associated project (e.g. billable or internal).
	ProjectType *ResourceBookingProjectType `json:"project_type,omitempty"`

	// Rejected Whether this booking has been rejected.
	Rejected *interface{} `json:"rejected,omitempty"`

	// RejectedAt Date when the booking was rejected.
	RejectedAt *time.Time `json:"rejected_at,omitempty"`

	// RejectedReason Reason provided when the booking was rejected.
	RejectedReason *string `json:"rejected_reason,omitempty"`

	// Rejecter The person who rejected this booking.
	Rejecter *interface{} `json:"rejecter,omitempty"`

	// ResourceRequest The resource request this booking fulfills, if applicable.
	ResourceRequest *interface{} `json:"resource_request,omitempty"`

	// ResourceRequestId ID of the resource request this booking fulfills.
	ResourceRequestId *int `json:"resource_request_id,omitempty"`

	// ScenarioItem The scenario item this booking is linked to, if created from a scenario.
	ScenarioItem *interface{} `json:"scenario_item,omitempty"`

	// Service The budget service being scheduled in this booking.
	Service *interface{} `json:"service,omitempty"`

	// ServiceId The ID of the service this booking is scheduled against.
	ServiceId *int `json:"service_id,omitempty"`

	// StageType The stage type of the booking within the resource planning workflow.
	StageType *ResourceBookingStageType `json:"stage_type,omitempty"`

	// StartedOn The start date of the booking.
	StartedOn *openapi_types.Date `json:"started_on,omitempty"`

	// Status The current approval status of the booking (e.g. pending, approved, rejected).
	Status *interface{} `json:"status,omitempty"`

	// Tags Tags associated with this booking.
	Tags *int `json:"tags,omitempty"`

	// Task The task associated with this booking, if applicable.
	Task *interface{} `json:"task,omitempty"`

	// TaskId The ID of the task associated with this booking, if applicable.
	TaskId *int `json:"task_id,omitempty"`

	// Time The booked time in minutes per day.
	Time *int `json:"time,omitempty"`

	// TotalTime The total booked time in minutes across the entire booking period.
	TotalTime *int `json:"total_time,omitempty"`

	// TotalWorkingDays The total number of working days covered by this booking.
	TotalWorkingDays *int `json:"total_working_days,omitempty"`

	// UpdatedAt Timestamp when this booking was last updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`

	// Updater The person who last updated this booking.
	Updater *interface{} `json:"updater,omitempty"`

	// UseSalaryCurrency When true, cost calculations use the person's salary currency instead of the service currency.
	UseSalaryCurrency *bool `json:"use_salary_currency,omitempty"`

	// WithDraft When true, draft bookings are included in availability and planning views.
	WithDraft *bool `json:"with_draft,omitempty"`
}

// ResourceBookingApprovalStatus Whether the booking has been approved. Reflects the overall approval_status.
type ResourceBookingApprovalStatus int

// ResourceBookingBillingTypeId ID of the billing type of the associated service.
type ResourceBookingBillingTypeId int

// ResourceBookingBookingMethodId ID of the booking method used to create this booking (e.g. hours per day, percentage, total hours).
type ResourceBookingBookingMethodId int

// ResourceBookingPersonType Type of the assigned person (e.g. employee, contractor, placeholder).
type ResourceBookingPersonType int

// ResourceBookingProjectType Type of the associated project (e.g. billable or internal).
type ResourceBookingProjectType int

// ResourceBookingStageType The stage type of the booking within the resource planning workflow.
type ResourceBookingStageType int

// ResourceEvent An absence event type (e.g. vacation, sick leave) used to categorize time-off bookings in the resource planner.
type ResourceEvent struct {
	// AbsenceType The absence category of this event, either time_off (standard time-off) or remote_work.
	AbsenceType *ResourceEventAbsenceType `json:"absence_type,omitempty"`

	// ArchivedAt Timestamp when this event was archived, or null if it is still active.
	ArchivedAt *time.Time `json:"archived_at,omitempty"`

	// ColorId ID of the color associated with this event for display purposes.
	ColorId     *int    `json:"color_id,omitempty"`
	Description *string `json:"description,omitempty"`

	// EventTypeId ID of the event type indicating whether this absence is paid (1) or unpaid (2).
	EventTypeId *ResourceEventEventTypeId `json:"event_type_id,omitempty"`

	// HalfDayBookings When true, bookings for this event can be created in half-day increments.
	HalfDayBookings *bool `json:"half_day_bookings,omitempty"`

	// IconId The icon identifier used to visually represent this event in the UI.
	IconId *string `json:"icon_id,omitempty"`

	// Id The unique identifier of this event.
	Id *int `json:"id,omitempty"`

	// LimitationType The limitation type of this event used for filtering (limited by days, limited by hours, or unlimited by hours).
	LimitationType *ResourceEventLimitationType `json:"limitation_type,omitempty"`

	// LimitationTypeId ID of the limitation type controlling how time-off for this event is tracked: limited by days (2), limited by hours (3), or unlimited by hours (4).
	LimitationTypeId *ResourceEventLimitationTypeId `json:"limitation_type_id,omitempty"`

	// Limited When true, this event has a limit on the amount of time-off that can be booked.
	Limited *bool `json:"limited,omitempty"`

	// Name The display name of this event.
	Name *string `json:"name,omitempty"`

	// Organization The organization this event belongs to.
	Organization *interface{} `json:"organization,omitempty"`

	// Status The archival status of this event, either active (1) or archived (2).
	Status *ResourceEventStatus `json:"status,omitempty"`

	// SyncPersonalIntegrations When true, bookings for this event are automatically synced to personal calendar integrations.
	SyncPersonalIntegrations *bool `json:"sync_personal_integrations,omitempty"`
}

// ResourceEventAbsenceType The absence category of this event, either time_off (standard time-off) or remote_work.
type ResourceEventAbsenceType string

// ResourceEventEventTypeId ID of the event type indicating whether this absence is paid (1) or unpaid (2).
type ResourceEventEventTypeId int

// ResourceEventLimitationType The limitation type of this event used for filtering (limited by days, limited by hours, or unlimited by hours).
type ResourceEventLimitationType int

// ResourceEventLimitationTypeId ID of the limitation type controlling how time-off for this event is tracked: limited by days (2), limited by hours (3), or unlimited by hours (4).
type ResourceEventLimitationTypeId int

// ResourceEventStatus The archival status of this event, either active (1) or archived (2).
type ResourceEventStatus int

// ResourcePerson A person represents an employee, contractor, contact, or placeholder within the organization.
type ResourcePerson struct {
	// AccessibleDealId Filter by accessible deal ID — returns people who have access to the specified deal.
	AccessibleDealId *int `json:"accessible_deal_id,omitempty"`

	// AccessibleDocId Filter by accessible doc ID — returns people who have access to the specified document.
	AccessibleDocId *int `json:"accessible_doc_id,omitempty"`

	// AccessibleFilterId Filter by accessible filter ID — returns people who are members of the specified saved view or filter.
	AccessibleFilterId *string `json:"accessible_filter_id,omitempty"`

	// AccessibleProjectId Filter by accessible project ID — returns people who have access to the specified project.
	AccessibleProjectId *int `json:"accessible_project_id,omitempty"`

	// AccountId The organization (account) ID.
	AccountId *interface{} `json:"account_id,omitempty"`

	// Agent The AI agent account linked to this person, if this person represents an AI agent.
	Agent *bool `json:"agent,omitempty"`

	// ApprovalPolicyAssignment The approval policy assignment for this person.
	ApprovalPolicyAssignment *interface{} `json:"approval_policy_assignment,omitempty"`

	// ApprovalPolicyId ID of the approval policy assigned to this person for time-off and booking approvals.
	ApprovalPolicyId *int `json:"approval_policy_id,omitempty"`

	// ApprovalWorkflowId Filter by approval workflow ID — returns people who have approvals in the specified workflow.
	ApprovalWorkflowId *int `json:"approval_workflow_id,omitempty"`

	// ArchivedAt Timestamp when this person was archived, or null if not archived.
	ArchivedAt *time.Time `json:"archived_at,omitempty"`

	// Autotracking Whether automatic time tracking is enabled for this person.
	Autotracking *bool `json:"autotracking,omitempty"`

	// Availabilities The person's work availability windows.
	Availabilities *interface{} `json:"availabilities,omitempty"`

	// AvatarUrl URL of the person's avatar thumbnail.
	AvatarUrl *string `json:"avatar_url,omitempty"`

	// BookingsAfter Filter by bookings_after date — used with resourcing filters to find people with bookings ending on or after this date.
	BookingsAfter *openapi_types.Date `json:"bookings_after,omitempty"`

	// BookingsBefore Filter by bookings_before date — used with resourcing filters to find people with bookings starting on or before this date.
	BookingsBefore *openapi_types.Date `json:"bookings_before,omitempty"`

	// Champion Whether this person is a champion contact.
	Champion *interface{} `json:"champion,omitempty"`

	// ColorId Color identifier used to visually distinguish this person in the UI.
	ColorId *int `json:"color_id,omitempty"`

	// Company The company (client) this person belongs to.
	Company *interface{} `json:"company,omitempty"`

	// CompanyId Filter by company (client) ID.
	CompanyId *int `json:"company_id,omitempty"`

	// CompanyName The name of the company this person belongs to.
	CompanyName *interface{} `json:"company_name,omitempty"`

	// Contact Additional contact data for the person, such as phone numbers and addresses.
	Contact *map[string]interface{} `json:"contact,omitempty"`

	// CreatedAt Timestamp when this person was created.
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// CustomFieldAttachments File attachments associated with this person via custom fields.
	CustomFieldAttachments *interface{} `json:"custom_field_attachments,omitempty"`

	// CustomFieldPeople People referenced in custom field values for this person.
	CustomFieldPeople *interface{} `json:"custom_field_people,omitempty"`

	// CustomFields Custom field values for this person.
	CustomFields *map[string]interface{} `json:"custom_fields,omitempty"`

	// CustomRole The custom role (permission set) assigned to this person.
	CustomRole *interface{} `json:"custom_role,omitempty"`

	// CustomRoleId ID of the custom role assigned to this person, if any.
	CustomRoleId *int `json:"custom_role_id,omitempty"`

	// DeactivatedAt Timestamp when this person was deactivated, or null if currently active.
	DeactivatedAt *time.Time `json:"deactivated_at,omitempty"`

	// EligibleReplacementManagers Filter for people eligible to be replacement managers for the specified person ID.
	EligibleReplacementManagers *int `json:"eligible_replacement_managers,omitempty"`

	// Email The person's email address.
	Email *string `json:"email,omitempty"`

	// ExternalId External identifier for syncing this person with an external system.
	ExternalId *string `json:"external_id,omitempty"`

	// ExternalSync Whether this person is managed by an external sync integration.
	ExternalSync *bool `json:"external_sync,omitempty"`

	// FirstName The person's first name.
	FirstName *string `json:"first_name,omitempty"`

	// FullQuery Full text search filter — matches against name and other indexed fields.
	FullQuery *string `json:"full_query,omitempty"`

	// FuzzyDates Fuzzy date filter for approximate date matching.
	FuzzyDates *string `json:"fuzzy_dates,omitempty"`

	// FuzzyPeople Fuzzy people filter for approximate person name matching.
	FuzzyPeople *string `json:"fuzzy_people,omitempty"`

	// GranularNotificationPreferences Granular notification preferences for this person.
	GranularNotificationPreferences *map[string]interface{} `json:"granular_notification_preferences,omitempty"`

	// HolidayCalendarId ID of the holiday calendar assigned to this person for scheduling and time-off calculations.
	HolidayCalendarId *int `json:"holiday_calendar_id,omitempty"`

	// HrmTypeId HRM type ID: 1 for employee, 2 for contact. Null for placeholders.
	HrmTypeId *ResourcePersonHrmTypeId `json:"hrm_type_id,omitempty"`

	// Id The unique identifier of the person.
	Id     *int         `json:"id,omitempty"`
	Import *interface{} `json:"import,omitempty"`

	// InvitedAt Timestamp when the invitation email was sent to this person.
	InvitedAt *time.Time `json:"invited_at,omitempty"`

	// IsUser Whether this person has an associated user account and can log in.
	IsUser *interface{} `json:"is_user,omitempty"`

	// JoinedAt Date when this person joined the organization.
	JoinedAt *time.Time `json:"joined_at,omitempty"`

	// JumpQuery Quick jump search filter — matches against name for navigation shortcuts.
	JumpQuery *string `json:"jump_query,omitempty"`

	// LastActivityAt Timestamp of the last recorded activity for this person across the platform.
	LastActivityAt *time.Time `json:"last_activity_at,omitempty"`

	// LastName The person's last name.
	LastName *string `json:"last_name,omitempty"`

	// LastSeenAt Timestamp when this person was last seen active in the application.
	LastSeenAt *time.Time `json:"last_seen_at,omitempty"`

	// Manager The person's manager.
	Manager *interface{} `json:"manager,omitempty"`

	// ManagerId ID of the person who is this person's direct manager.
	ManagerId *int `json:"manager_id,omitempty"`

	// Name The person's full name (first and last combined).
	Name *interface{} `json:"name,omitempty"`

	// Nickname The person's nickname or preferred display name.
	Nickname *string `json:"nickname,omitempty"`

	// OffboardingId ID of the offboarding process associated with this person's deactivation.
	OffboardingId *int `json:"offboarding_id,omitempty"`

	// OffboardingStatus Current offboarding status: not_initiated, in_progress, or completed.
	OffboardingStatus *ResourcePersonOffboardingStatus `json:"offboarding_status,omitempty"`

	// Organization The organization this person belongs to.
	Organization *interface{} `json:"organization,omitempty"`

	// OriginalAvatarUrl URL of the person's original full-size avatar image.
	OriginalAvatarUrl *string `json:"original_avatar_url,omitempty"`

	// Permissions Filter by permission set — returns people with the specified permission slugs.
	Permissions *string `json:"permissions,omitempty"`

	// PersonType Filter by person type — values: user (can log in), contact (external), placeholder (resource planning), agent.
	PersonType *string `json:"person_type,omitempty"`

	// Placeholder Whether this person is a placeholder used for resource planning, without a real user account.
	Placeholder *bool `json:"placeholder,omitempty"`

	// ProjectId Filter by project ID — returns people who are members of the specified project.
	ProjectId *int `json:"project_id,omitempty"`

	// ProjectWatching Filter by project_watching — returns people who are auto-subscribed to the specified project.
	ProjectWatching *int `json:"project_watching,omitempty"`

	// Query Text search filter — matches by full name (exact) or contains partial name.
	Query *string `json:"query,omitempty"`

	// RoleId Filter by built-in role type ID.
	RoleId *int `json:"role_id,omitempty"`

	// SampleData Whether this person was created as part of sample/demo data.
	SampleData *bool `json:"sample_data,omitempty"`

	// Schedulable Filter for schedulable people — returns employees, contractors, and placeholders who can be booked.
	Schedulable *bool `json:"schedulable,omitempty"`

	// ServiceId Filter by service ID — returns people who can track time on the specified service.
	ServiceId *int `json:"service_id,omitempty"`

	// ServiceTypeId Filter by service type ID — returns people assigned to the specified service types.
	ServiceTypeId *int `json:"service_type_id,omitempty"`

	// ServiceTypes The service types this person delivers.
	ServiceTypes *interface{} `json:"service_types,omitempty"`

	// Status Filter by person status: 1 (active) or 2 (deactivated).
	Status *ResourcePersonStatus `json:"status,omitempty"`

	// StatusEmoji Emoji shown as the person's current status indicator.
	StatusEmoji *string `json:"status_emoji,omitempty"`

	// StatusExpiresAt Timestamp when the current status emoji and text expire.
	StatusExpiresAt *time.Time `json:"status_expires_at,omitempty"`

	// StatusText Short text message shown as the person's current status.
	StatusText *string `json:"status_text,omitempty"`

	// SubscribableId Filter by subscribable ID — returns subscribers of the specified resource.
	SubscribableId *int `json:"subscribable_id,omitempty"`

	// SubscribableType Filter by subscribable type — the resource type to match subscribers against.
	SubscribableType *string `json:"subscribable_type,omitempty"`

	// SubscriberIds IDs of people subscribed to follow this person.
	SubscriberIds *interface{} `json:"subscriber_ids,omitempty"`

	// Subsidiary The subsidiary (workplace) this person is associated with.
	Subsidiary *interface{} `json:"subsidiary,omitempty"`

	// SubsidiaryId ID of the subsidiary company this person belongs to, if any.
	SubsidiaryId *int `json:"subsidiary_id,omitempty"`

	// TagList Comma-separated list of tags applied to this person.
	TagList *interface{} `json:"tag_list,omitempty"`

	// Tags Tags applied to this person.
	Tags *string `json:"tags,omitempty"`

	// Team Filter by team ID — returns people who belong to the specified team(s).
	Team *int `json:"team,omitempty"`

	// Teams The teams this person belongs to.
	Teams *interface{} `json:"teams,omitempty"`

	// TimeOffStatusSync Whether this person's time-off status is synced from an external calendar.
	TimeOffStatusSync *bool `json:"time_off_status_sync,omitempty"`

	// TimeTrackingPolicy The time tracking policy assigned to this person.
	TimeTrackingPolicy *interface{} `json:"time_tracking_policy,omitempty"`

	// TimeTrackingPolicyId ID of the time tracking policy applied to this person.
	TimeTrackingPolicyId *int `json:"time_tracking_policy_id,omitempty"`

	// TimeUnlocked Whether the person's time entries are unlocked for editing outside the normal window.
	TimeUnlocked *bool `json:"time_unlocked,omitempty"`

	// TimeUnlockedEndDate End date of the time unlock window.
	TimeUnlockedEndDate *openapi_types.Date `json:"time_unlocked_end_date,omitempty"`

	// TimeUnlockedInterval Number of days in the time unlock interval.
	TimeUnlockedInterval *int `json:"time_unlocked_interval,omitempty"`

	// TimeUnlockedOn The specific date on which the time unlock was applied.
	TimeUnlockedOn *openapi_types.Date `json:"time_unlocked_on,omitempty"`

	// TimeUnlockedPeriodId Period identifier for the time unlock.
	TimeUnlockedPeriodId *int `json:"time_unlocked_period_id,omitempty"`

	// TimeUnlockedStartDate Start date of the time unlock window.
	TimeUnlockedStartDate *openapi_types.Date `json:"time_unlocked_start_date,omitempty"`

	// TimesheetSubmissionDisabled Whether timesheet submission is disabled for this person.
	TimesheetSubmissionDisabled *bool `json:"timesheet_submission_disabled,omitempty"`

	// Title The person's job title (e.g. CEO, Manager, Developer).
	Title *string `json:"title,omitempty"`

	// TwoFactorAuth Whether two-factor authentication is enabled for this person's user account.
	TwoFactorAuth *bool `json:"two_factor_auth,omitempty"`

	// UserId The ID of the user account linked to this person, if any.
	UserId *int `json:"user_id,omitempty"`

	// Virtual Whether this is a virtual person record.
	Virtual *bool `json:"virtual,omitempty"`
}

// ResourcePersonHrmTypeId HRM type ID: 1 for employee, 2 for contact. Null for placeholders.
type ResourcePersonHrmTypeId int

// ResourcePersonOffboardingStatus Current offboarding status: not_initiated, in_progress, or completed.
type ResourcePersonOffboardingStatus string

// ResourcePersonStatus Filter by person status: 1 (active) or 2 (deactivated).
type ResourcePersonStatus int

// ResourceProject A workspace for tasks, documents, surveys, and budgets. Projects can be billable (client work) or internal (overhead), and provide the organizational structure for team collaboration.
type ResourceProject struct {
	// ArchivedAt Archived at date
	ArchivedAt *time.Time `json:"archived_at,omitempty"`

	// BudgetId ID of a budget linked to this project.
	BudgetId *int `json:"budget_id,omitempty"`

	// Company The client company linked to this project.
	Company *interface{} `json:"company,omitempty"`

	// CompanyId ID of the client company associated with this project.
	CompanyId *int `json:"company_id,omitempty"`

	// CompanyName Name of the client company associated with this project.
	CompanyName *interface{} `json:"company_name,omitempty"`

	// Cost Total cost across all open budgets for this project, in the organization's base currency.
	Cost *int `json:"cost,omitempty"`

	// CreatedAt Timestamp when this project was created.
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// CustomFieldAttachments File attachments referenced by custom field values on this project.
	CustomFieldAttachments *interface{} `json:"custom_field_attachments,omitempty"`

	// CustomFieldPeople People referenced by person-type custom field values on this project.
	CustomFieldPeople *interface{} `json:"custom_field_people,omitempty"`

	// CustomFields Custom field values for this project, keyed by custom field ID.
	CustomFields *map[string]interface{} `json:"custom_fields,omitempty"`

	// DuplicationStatus Background duplication status when copying from a template. One of: idle, in_progress, done, failed.
	DuplicationStatus *ResourceProjectDuplicationStatus `json:"duplication_status,omitempty"`

	// EstimatedTime Total estimated time across all open budgets for this project, in minutes.
	EstimatedTime *int `json:"estimated_time,omitempty"`

	// ForTracking Whether this project is eligible for time tracking (i.e. active).
	ForTracking *bool `json:"for_tracking,omitempty"`

	// FullQuery Full-text search query across all project content fields.
	FullQuery *string `json:"full_query,omitempty"`

	// FuzzyDates Fuzzy date range filter for project start/end dates.
	FuzzyDates *openapi_types.Date `json:"fuzzy_dates,omitempty"`

	// FuzzyPeople Fuzzy person filter — matches projects by associated people.
	FuzzyPeople *int `json:"fuzzy_people,omitempty"`

	// Id Unique project ID.
	Id     *int         `json:"id,omitempty"`
	Import *interface{} `json:"import,omitempty"`

	// JumpQuery Quick-jump search query for project navigation.
	JumpQuery *string `json:"jump_query,omitempty"`

	// LastActivityAt Timestamp of the most recent activity on this project.
	LastActivityAt *time.Time `json:"last_activity_at,omitempty"`

	// LastActor The person who last performed an activity on this project.
	LastActor *interface{} `json:"last_actor,omitempty"`

	// Name Project name.
	Name *string `json:"name,omitempty"`

	// Number Auto-generated unique project number.
	Number *string `json:"number,omitempty"`

	// Organization The organization this project belongs to.
	Organization *interface{} `json:"organization,omitempty"`

	// PageCustomFieldsIds Ordered list of custom field IDs enabled for pages in this project.
	PageCustomFieldsIds *map[string]interface{} `json:"page_custom_fields_ids,omitempty"`

	// PageCustomFieldsPositions Display position order for page custom fields in this project.
	PageCustomFieldsPositions *map[string]interface{} `json:"page_custom_fields_positions,omitempty"`

	// ParentCompanyId ID of the parent company of the client linked to this project, used for hierarchical company filtering.
	ParentCompanyId *int `json:"parent_company_id,omitempty"`

	// PendingInvoicing Total amount pending invoicing across all open budgets for this project, in the organization's base currency.
	PendingInvoicing *int `json:"pending_invoicing,omitempty"`

	// PersonId ID of a person who is a member of this project.
	PersonId *int `json:"person_id,omitempty"`

	// Preferences Project-level display and behavior preferences.
	Preferences *map[string]interface{} `json:"preferences,omitempty"`

	// Profit Total profit across all open budgets for this project, in the organization's base currency.
	Profit *int `json:"profit,omitempty"`

	// ProfitMargin Profit margin percentage across all open budgets for this project.
	ProfitMargin *int `json:"profit_margin,omitempty"`

	// ProjectColor Display color label for the project.
	ProjectColor *int `json:"project_color,omitempty"`

	// ProjectColorId Display color ID for the project.
	ProjectColorId *int `json:"project_color_id,omitempty"`

	// ProjectId Alias for the project ID field.
	ProjectId *int `json:"project_id,omitempty"`

	// ProjectManager The project manager responsible for this project.
	ProjectManager *interface{} `json:"project_manager,omitempty"`

	// ProjectManagerId ID of the project manager (responsible person).
	ProjectManagerId *int `json:"project_manager_id,omitempty"`

	// ProjectNumber Formatted project number string (e.g. ACME-001).
	ProjectNumber *string `json:"project_number,omitempty"`

	// ProjectType Human-readable project type label.
	ProjectType *ResourceProjectProjectType `json:"project_type,omitempty"`

	// ProjectTypeId Whether this project is billable client work (1) or internal overhead (2).
	ProjectTypeId *ResourceProjectProjectTypeId `json:"project_type_id,omitempty"`

	// PublicAccess Deprecated. No-op — has no effect.
	PublicAccess *bool `json:"public_access,omitempty"`

	// Query Full-text search query across project fields.
	Query *string `json:"query,omitempty"`

	// ResponsibleId ID of the responsible person (project manager) for this project.
	ResponsibleId *int `json:"responsible_id,omitempty"`

	// Revenue Total revenue across all open budgets for this project, in the organization's base currency.
	Revenue *int `json:"revenue,omitempty"`

	// SampleData Whether this project was created with sample/demo data.
	SampleData *bool `json:"sample_data,omitempty"`

	// Status Project status. 1 = active, 2 = archived.
	Status *ResourceProjectStatus `json:"status,omitempty"`

	// TagColors Color mappings for project tags, keyed by tag name.
	TagColors *string `json:"tag_colors,omitempty"`

	// TaskCustomFieldsIds Ordered list of custom field IDs enabled for tasks in this project.
	TaskCustomFieldsIds *map[string]interface{} `json:"task_custom_fields_ids,omitempty"`

	// TaskCustomFieldsPositions Display position order for task custom fields in this project.
	TaskCustomFieldsPositions *map[string]interface{} `json:"task_custom_fields_positions,omitempty"`

	// Template Whether this project is a template.
	Template *string `json:"template,omitempty"`

	// TemplateObject The template this project was created from, if any.
	TemplateObject *interface{} `json:"template_object,omitempty"`

	// TotalWorkedTime Total worked time across all budgets (including closed) for this project, in minutes.
	TotalWorkedTime *int `json:"total_worked_time,omitempty"`

	// WithTemplates When true, includes project templates in the results (templates are excluded by default).
	WithTemplates *bool `json:"with_templates,omitempty"`

	// WorkedTime Total worked time across all open budgets for this project, in minutes.
	WorkedTime *int `json:"worked_time,omitempty"`

	// Workflow The task workflow used in this project.
	Workflow *interface{} `json:"workflow,omitempty"`

	// WorkflowId ID of the task workflow used in this project.
	WorkflowId *int `json:"workflow_id,omitempty"`
}

// ResourceProjectDuplicationStatus Background duplication status when copying from a template. One of: idle, in_progress, done, failed.
type ResourceProjectDuplicationStatus string

// ResourceProjectProjectType Human-readable project type label.
type ResourceProjectProjectType int

// ResourceProjectProjectTypeId Whether this project is billable client work (1) or internal overhead (2).
type ResourceProjectProjectTypeId int

// ResourceProjectStatus Project status. 1 = active, 2 = archived.
type ResourceProjectStatus int

// ResourceService A line item on a deal or budget that defines billing type, rate, and tracking rules. Services connect time tracking, resource scheduling, and invoicing for a specific scope of work.
type ResourceService struct {
	// After Earliest bookable date for this service.
	After *openapi_types.Date `json:"after,omitempty"`

	// Before Latest bookable date for this service.
	Before *openapi_types.Date `json:"before,omitempty"`

	// Billable Whether this service is billable to the client.
	Billable *bool `json:"billable,omitempty"`

	// BillableTime Billable hours tracked on the service.
	BillableTime *int `json:"billable_time,omitempty"`

	// BillingType Billing type display name.
	BillingType *ResourceServiceBillingType `json:"billing_type,omitempty"`

	// BillingTypeId How this service is billed: hourly, daily, fixed price, or non-billable.
	BillingTypeId *ResourceServiceBillingTypeId `json:"billing_type_id,omitempty"`

	// BookableAfter Start date from which resource bookings are allowed.
	BookableAfter *openapi_types.Date `json:"bookable_after,omitempty"`

	// BookableBefore End date until which resource bookings are allowed.
	BookableBefore *openapi_types.Date `json:"bookable_before,omitempty"`

	// BookableDate Filters services to those bookable on the specified date, based on the budget's active period. Services on deals are always included.
	BookableDate *openapi_types.Date `json:"bookable_date,omitempty"`

	// BookableDateForPeriod **Deprecated — use `bookable_date` instead**, which now returns identical results. Filters services to those bookable on the specified date, based on the budget's active period. This filter will be removed in a future API version.
	BookableDateForPeriod *openapi_types.Date `json:"bookable_date_for_period,omitempty"`

	// BookedTime Total scheduled (booked) time for this service.
	BookedTime *int `json:"booked_time,omitempty"`

	// BookingTrackingEnabled Whether resource bookings are enabled for this service.
	BookingTrackingEnabled *bool `json:"booking_tracking_enabled,omitempty"`

	// Budget The deal budget this service is part of.
	Budget *interface{} `json:"budget,omitempty"`

	// BudgetCapEnabled Whether a hard budget cap prevents tracking beyond the budget total.
	BudgetCapEnabled *bool `json:"budget_cap_enabled,omitempty"`

	// BudgetDate The date of the budget period this service belongs to.
	BudgetDate *openapi_types.Date `json:"budget_date,omitempty"`

	// BudgetId The ID of the budget this service belongs to.
	BudgetId *int `json:"budget_id,omitempty"`

	// BudgetRemaining Budget amount remaining unused.
	BudgetRemaining *int `json:"budget_remaining,omitempty"`

	// BudgetStatus Current status of the service budget (e.g. on track, over budget).
	BudgetStatus *ResourceServiceBudgetStatus `json:"budget_status,omitempty"`

	// BudgetTotal Total budget for this service.
	BudgetTotal *interface{} `json:"budget_total,omitempty"`

	// BudgetTotalDefault Total budget for this service in the organization's default currency.
	BudgetTotalDefault *interface{} `json:"budget_total_default,omitempty"`

	// BudgetTotalNormalized Total budget for this service in the organization's normalized currency.
	BudgetTotalNormalized *interface{} `json:"budget_total_normalized,omitempty"`

	// BudgetUsed Budget consumed so far.
	BudgetUsed *interface{} `json:"budget_used,omitempty"`

	// BudgetUsedDefault Budget consumed so far in the organization's default currency.
	BudgetUsedDefault *interface{} `json:"budget_used_default,omitempty"`

	// BudgetUsedNormalized Budget consumed so far in the organization's normalized currency.
	BudgetUsedNormalized *interface{} `json:"budget_used_normalized,omitempty"`

	// BudgetedTime Budgeted hours allocated for this service.
	BudgetedTime *int `json:"budgeted_time,omitempty"`

	// BudgetsAndDeals List of related deals and budgets for this service.
	BudgetsAndDeals *interface{} `json:"budgets_and_deals,omitempty"`

	// Company The company (client) linked to the deal this service is on.
	Company *interface{} `json:"company,omitempty"`

	// CompanyId The company (client) linked to the deal this service is on.
	CompanyId *int `json:"company_id,omitempty"`

	// ContractId The recurring contract this service originated from.
	ContractId *int `json:"contract_id,omitempty"`

	// Cost Total cost including labor and expenses.
	Cost *interface{} `json:"cost,omitempty"`

	// CostDefault Total cost including labor and expenses in the organization's default currency.
	CostDefault *interface{} `json:"cost_default,omitempty"`

	// CostNormalized Total cost including labor and expenses in the organization's normalized currency.
	CostNormalized *interface{} `json:"cost_normalized,omitempty"`

	// Currency Currency code for this service's financial values.
	Currency *interface{} `json:"currency,omitempty"`

	// CurrencyDefault Currency code in the organization's default currency.
	CurrencyDefault *interface{} `json:"currency_default,omitempty"`

	// CurrencyNormalized Currency code in the organization's normalized currency.
	CurrencyNormalized *interface{} `json:"currency_normalized,omitempty"`

	// CustomFieldAttachments Files in file-type custom fields.
	CustomFieldAttachments *interface{} `json:"custom_field_attachments,omitempty"`

	// CustomFieldPeople People in person-type custom fields.
	CustomFieldPeople *interface{} `json:"custom_field_people,omitempty"`

	// CustomFields Custom field values on this service.
	CustomFields *map[string]interface{} `json:"custom_fields,omitempty"`

	// Deal The deal or budget this service is part of.
	Deal *interface{} `json:"deal,omitempty"`

	// DealId The deal or budget this service is part of.
	DealId *int `json:"deal_id,omitempty"`

	// DealStageId The pipeline stage the parent deal is in.
	DealStageId *int `json:"deal_stage_id,omitempty"`

	// DealStatusId The deal status of the parent deal.
	DealStatusId *int `json:"deal_status_id,omitempty"`

	// DeletedAt Soft-deletion timestamp.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`

	// Discount Discount amount subtracted from the service price.
	Discount *float32 `json:"discount,omitempty"`

	// DiscountAmount Total discount in monetary terms.
	DiscountAmount *interface{} `json:"discount_amount,omitempty"`

	// DiscountAmountDefault Total discount in monetary terms in the organization's default currency.
	DiscountAmountDefault *interface{} `json:"discount_amount_default,omitempty"`

	// DiscountAmountNormalized Total discount in monetary terms in the organization's normalized currency.
	DiscountAmountNormalized *interface{} `json:"discount_amount_normalized,omitempty"`

	// EditorConfig Rich text editor configuration.
	EditorConfig *map[string]interface{} `json:"editor_config,omitempty"`

	// EstimatedCost Estimated cost based on estimated time and cost rates.
	EstimatedCost *float32 `json:"estimated_cost,omitempty"`

	// EstimatedCostDefault Estimated cost based on estimated time and cost rates in the organization's default currency.
	EstimatedCostDefault *interface{} `json:"estimated_cost_default,omitempty"`

	// EstimatedCostNormalized Estimated cost based on estimated time and cost rates in the organization's normalized currency.
	EstimatedCostNormalized *interface{} `json:"estimated_cost_normalized,omitempty"`

	// EstimatedTime Estimated hours for this service.
	EstimatedTime *int `json:"estimated_time,omitempty"`

	// ExpenseAmount Total expense amount on this service.
	ExpenseAmount *interface{} `json:"expense_amount,omitempty"`

	// ExpenseAmountDefault Total expense amount on this service in the organization's default currency.
	ExpenseAmountDefault *interface{} `json:"expense_amount_default,omitempty"`

	// ExpenseAmountNormalized Total expense amount on this service in the organization's normalized currency.
	ExpenseAmountNormalized *interface{} `json:"expense_amount_normalized,omitempty"`

	// ExpenseBillableAmount Billable portion of expenses.
	ExpenseBillableAmount *interface{} `json:"expense_billable_amount,omitempty"`

	// ExpenseBillableAmountDefault Billable portion of expenses in the organization's default currency.
	ExpenseBillableAmountDefault *interface{} `json:"expense_billable_amount_default,omitempty"`

	// ExpenseBillableAmountNormalized Billable portion of expenses in the organization's normalized currency.
	ExpenseBillableAmountNormalized *interface{} `json:"expense_billable_amount_normalized,omitempty"`

	// ExpenseCost Labor cost from worked time at cost rates.
	ExpenseCost *interface{} `json:"expense_cost,omitempty"`

	// ExpenseTrackingEnabled Whether expenses can be logged against this service.
	ExpenseTrackingEnabled *bool `json:"expense_tracking_enabled,omitempty"`

	// ExplicitAccess When true, filters services to those the current user has been explicitly granted access to.
	ExplicitAccess *bool `json:"explicit_access,omitempty"`

	// ForTracking Whether this service is available for time tracking.
	ForTracking *bool `json:"for_tracking,omitempty"`

	// FutureBookedTime Future scheduled time remaining.
	FutureBookedTime *int `json:"future_booked_time,omitempty"`

	// FutureBudgetUsed Budget that will be consumed by future bookings.
	FutureBudgetUsed *interface{} `json:"future_budget_used,omitempty"`

	// FutureBudgetUsedDefault Budget that will be consumed by future bookings in the organization's default currency.
	FutureBudgetUsedDefault *interface{} `json:"future_budget_used_default,omitempty"`

	// FutureBudgetUsedNormalized Budget that will be consumed by future bookings in the organization's normalized currency.
	FutureBudgetUsedNormalized *interface{} `json:"future_budget_used_normalized,omitempty"`

	// FutureCost Projected cost from future scheduled bookings.
	FutureCost *interface{} `json:"future_cost,omitempty"`

	// FutureCostDefault Projected cost from future scheduled bookings in the organization's default currency.
	FutureCostDefault *interface{} `json:"future_cost_default,omitempty"`

	// FutureCostNormalized Projected cost from future scheduled bookings in the organization's normalized currency.
	FutureCostNormalized *interface{} `json:"future_cost_normalized,omitempty"`

	// FutureRevenue Revenue projected from future bookings.
	FutureRevenue *interface{} `json:"future_revenue,omitempty"`

	// FutureRevenueDefault Revenue projected from future bookings in the organization's default currency.
	FutureRevenueDefault *interface{} `json:"future_revenue_default,omitempty"`

	// FutureRevenueNormalized Revenue projected from future bookings in the organization's normalized currency.
	FutureRevenueNormalized *interface{} `json:"future_revenue_normalized,omitempty"`

	// Id Unique identifier of the service.
	Id     *int         `json:"id,omitempty"`
	Import *interface{} `json:"import,omitempty"`

	// InitialServiceId ID of the first service in a rollover chain.
	InitialServiceId *int `json:"initial_service_id,omitempty"`

	// LeftToScheduleTime Time remaining to be scheduled on this service.
	LeftToScheduleTime *int `json:"left_to_schedule_time,omitempty"`

	// LimitationType Budget cap enforcement type (soft warning vs hard cap).
	LimitationType *ResourceServiceLimitationType `json:"limitation_type,omitempty"`

	// Markup Markup amount added to the service price.
	Markup *float32 `json:"markup,omitempty"`

	// MarkupAmount Total markup in monetary terms.
	MarkupAmount *interface{} `json:"markup_amount,omitempty"`

	// MarkupAmountDefault Total markup in monetary terms in the organization's default currency.
	MarkupAmountDefault *interface{} `json:"markup_amount_default,omitempty"`

	// MarkupAmountNormalized Total markup in monetary terms in the organization's normalized currency.
	MarkupAmountNormalized *interface{} `json:"markup_amount_normalized,omitempty"`

	// Name Name of the service.
	Name *string `json:"name,omitempty"`

	// Organization The organization this service belongs to.
	Organization *interface{} `json:"organization,omitempty"`

	// OriginDealId The ID of the original deal before rollover.
	OriginDealId *int `json:"origin_deal_id,omitempty"`

	// OriginServiceId ID of the original service if this was duplicated or rolled over.
	OriginServiceId *int `json:"origin_service_id,omitempty"`

	// Person The person assigned to this service (for person-scoped services).
	Person *interface{} `json:"person,omitempty"`

	// PersonId The person assigned to this service (for person-scoped services).
	PersonId *int `json:"person_id,omitempty"`

	// PipelineId The pipeline the parent deal belongs to.
	PipelineId *int `json:"pipeline_id,omitempty"`

	// Position Sort order within the deal's service list.
	Position *int `json:"position,omitempty"`

	// Price Unit price for this service.
	Price *float32 `json:"price,omitempty"`

	// PriceDefault Unit price for this service in the organization's default currency.
	PriceDefault *interface{} `json:"price_default,omitempty"`

	// PriceNormalized Unit price for this service in the organization's normalized currency.
	PriceNormalized *interface{} `json:"price_normalized,omitempty"`

	// Probability Win probability of the parent deal (percentage).
	Probability *int `json:"probability,omitempty"`

	// Profit Service profit: revenue minus costs.
	Profit *int `json:"profit,omitempty"`

	// ProfitDefault Service profit in the organization's default currency.
	ProfitDefault *interface{} `json:"profit_default,omitempty"`

	// ProfitMargin Profit as a percentage of revenue.
	ProfitMargin *float32 `json:"profit_margin,omitempty"`

	// ProfitNormalized Service profit in the organization's normalized currency.
	ProfitNormalized *interface{} `json:"profit_normalized,omitempty"`

	// ProjectId The project this service is linked to.
	ProjectId *int `json:"project_id,omitempty"`

	// ProjectName Name of the project this service is linked to.
	ProjectName *interface{} `json:"project_name,omitempty"`

	// ProjectType Type of the project (billable or overhead).
	ProjectType *ResourceServiceProjectType `json:"project_type,omitempty"`

	// ProjectedRevenue Expected revenue including future scheduled work.
	ProjectedRevenue *interface{} `json:"projected_revenue,omitempty"`

	// ProjectedRevenueDefault Expected revenue including future scheduled work in the organization's default currency.
	ProjectedRevenueDefault *interface{} `json:"projected_revenue_default,omitempty"`

	// ProjectedRevenueNormalized Expected revenue including future scheduled work in the organization's normalized currency.
	ProjectedRevenueNormalized *interface{} `json:"projected_revenue_normalized,omitempty"`

	// ProjectlessBudgets Whether this service belongs to a budget without a linked project.
	ProjectlessBudgets *bool `json:"projectless_budgets,omitempty"`

	// Quantity Number of units (hours, days, or pieces) for this service.
	Quantity *float32 `json:"quantity,omitempty"`

	// Query Full-text search query to filter services by name or description.
	Query *string `json:"query,omitempty"`

	// RemainingScheduledTime Time remaining to be scheduled on this service.
	RemainingScheduledTime *int `json:"remaining_scheduled_time,omitempty"`

	// ResponsibleId The person responsible for this service.
	ResponsibleId *int `json:"responsible_id,omitempty"`

	// RevampedUnit Whether this service uses the revamped unit system.
	RevampedUnit *ResourceServiceRevampedUnit `json:"revamped_unit,omitempty"`

	// Revenue Total revenue from this service.
	Revenue *interface{} `json:"revenue,omitempty"`

	// RevenueDefault Total revenue from this service in the organization's default currency.
	RevenueDefault *interface{} `json:"revenue_default,omitempty"`

	// RevenueNormalized Total revenue from this service in the organization's normalized currency.
	RevenueNormalized *interface{} `json:"revenue_normalized,omitempty"`

	// RolledOverTime Time rolled over from a previous retainer period.
	RolledOverTime *int `json:"rolled_over_time,omitempty"`

	// SalesStatusId The sales status ID of the parent deal.
	SalesStatusId *ResourceServiceSalesStatusId `json:"sales_status_id,omitempty"`

	// Section The section grouping this service within the deal.
	Section *interface{} `json:"section,omitempty"`

	// SectionId The section grouping this service within the deal.
	SectionId *int `json:"section_id,omitempty"`

	// ServiceType The work category this service belongs to.
	ServiceType *interface{} `json:"service_type,omitempty"`

	// ServiceTypeId The work category this service belongs to.
	ServiceTypeId *int `json:"service_type_id,omitempty"`

	// StageStatusId The stage status ID of the parent deal.
	StageStatusId *ResourceServiceStageStatusId `json:"stage_status_id,omitempty"`

	// StageType The stage type of the parent deal.
	StageType *ResourceServiceStageType `json:"stage_type,omitempty"`

	// SubsidiaryId The subsidiary associated with the parent deal.
	SubsidiaryId *int `json:"subsidiary_id,omitempty"`

	// TaskId The task this service is linked to.
	TaskId *int `json:"task_id,omitempty"`

	// Template Whether this service is a template.
	Template *bool `json:"template,omitempty"`

	// TimeTrackingEnabled Whether team members can track time against this service.
	TimeTrackingEnabled *bool `json:"time_tracking_enabled,omitempty"`

	// TrackableByPersonId Whether this service is trackable by a specific person.
	TrackableByPersonId *int `json:"trackable_by_person_id,omitempty"`

	// Type JSON:API resource type identifier.
	Type *int `json:"type,omitempty"`

	// UnapprovedTime Total unapproved time entries in minutes.
	UnapprovedTime *int `json:"unapproved_time,omitempty"`

	// Unit The tracking unit (hours, days, or pieces) for this service.
	Unit *ResourceServiceUnit `json:"unit,omitempty"`

	// UnitId Tracking unit: hours, days, or pieces.
	UnitId *ResourceServiceUnitId `json:"unit_id,omitempty"`

	// UpdatedAt Timestamp of the last update to this service.
	UpdatedAt *openapi_types.Date `json:"updated_at,omitempty"`

	// WithMemberships Whether this service has membership restrictions.
	WithMemberships *bool `json:"with_memberships,omitempty"`

	// WorkCost Labor cost from tracked time.
	WorkCost *interface{} `json:"work_cost,omitempty"`

	// WorkCostDefault Labor cost from tracked time in the organization's default currency.
	WorkCostDefault *interface{} `json:"work_cost_default,omitempty"`

	// WorkCostNormalized Labor cost from tracked time in the organization's normalized currency.
	WorkCostNormalized *interface{} `json:"work_cost_normalized,omitempty"`

	// WorkedCost Labor cost calculated from worked time.
	WorkedCost *interface{} `json:"worked_cost,omitempty"`

	// WorkedTime Total hours tracked on this service.
	WorkedTime *int `json:"worked_time,omitempty"`
}

// ResourceServiceBillingType Billing type display name.
type ResourceServiceBillingType int

// ResourceServiceBillingTypeId How this service is billed: hourly, daily, fixed price, or non-billable.
type ResourceServiceBillingTypeId int

// ResourceServiceBudgetStatus Current status of the service budget (e.g. on track, over budget).
type ResourceServiceBudgetStatus int

// ResourceServiceLimitationType Budget cap enforcement type (soft warning vs hard cap).
type ResourceServiceLimitationType string

// ResourceServiceProjectType Type of the project (billable or overhead).
type ResourceServiceProjectType int

// ResourceServiceRevampedUnit Whether this service uses the revamped unit system.
type ResourceServiceRevampedUnit int

// ResourceServiceSalesStatusId The sales status ID of the parent deal.
type ResourceServiceSalesStatusId int

// ResourceServiceStageStatusId The stage status ID of the parent deal.
type ResourceServiceStageStatusId int

// ResourceServiceStageType The stage type of the parent deal.
type ResourceServiceStageType int

// ResourceServiceUnit The tracking unit (hours, days, or pieces) for this service.
type ResourceServiceUnit int

// ResourceServiceUnitId Tracking unit: hours, days, or pieces.
type ResourceServiceUnitId int

// ResourceTimeEntry A time entry records the time a person has logged against a service on a deal or project, capturing the date, duration, and optionally a note describing the work done.
type ResourceTimeEntry struct {
	// After after of the time entry.
	After *openapi_types.Date `json:"after,omitempty"`

	// ApprovalPolicyId approval policy id of the time entry.
	ApprovalPolicyId *int `json:"approval_policy_id,omitempty"`

	// ApprovalStatuses Per-approver decisions on this time entry.
	ApprovalStatuses *interface{} `json:"approval_statuses,omitempty"`

	// Approved Whether this time entry has been approved.
	Approved *interface{} `json:"approved,omitempty"`

	// ApprovedAt Timestamp when the time entry was approved.
	ApprovedAt *time.Time `json:"approved_at,omitempty"`

	// Approver The person who approved this time entry.
	Approver *interface{} `json:"approver,omitempty"`

	// ApproverId approver id of the time entry.
	ApproverId *int `json:"approver_id,omitempty"`

	// AssignedApproverId assigned approver id of the time entry.
	AssignedApproverId *int `json:"assigned_approver_id,omitempty"`

	// Autotracked autotracked of the time entry.
	Autotracked *bool `json:"autotracked,omitempty"`

	// AwaitingApprovalFromApproverId awaiting approval from approver id of the time entry.
	AwaitingApprovalFromApproverId *int `json:"awaiting_approval_from_approver_id,omitempty"`

	// BaseCost Base labor cost before overhead (serialized from work_cost).
	BaseCost *interface{} `json:"base_cost,omitempty"`

	// Before before of the time entry.
	Before *openapi_types.Date `json:"before,omitempty"`

	// Billable Whether the associated service is billable.
	Billable *bool `json:"billable,omitempty"`

	// BillableTime Hours billable to clients (time + correction for billable services, zero for non-billable).
	BillableTime *int `json:"billable_time,omitempty"`

	// BillingTypeId Billing type of the associated service.
	BillingTypeId *ResourceTimeEntryBillingTypeId `json:"billing_type_id,omitempty"`

	// BookingId ID of the booking this time entry was created from.
	BookingId *int `json:"booking_id,omitempty"`

	// BudgetId ID of the deal/budget this time was tracked on.
	BudgetId *int `json:"budget_id,omitempty"`

	// BudgetTypeId Budget type ID of the associated deal.
	BudgetTypeId *int `json:"budget_type_id,omitempty"`

	// CalendarEventId ID of the calendar event this entry was created from, if applicable.
	CalendarEventId *string `json:"calendar_event_id,omitempty"`

	// CompanyId ID of the client company associated with the deal.
	CompanyId *int `json:"company_id,omitempty"`

	// Cost Total cost of tracked time, including labor and overhead costs.
	Cost *interface{} `json:"cost,omitempty"`

	// CostDefault Total cost in the organization's default currency.
	CostDefault *interface{} `json:"cost_default,omitempty"`

	// CostNormalized Total cost in the normalized reporting currency.
	CostNormalized *interface{} `json:"cost_normalized,omitempty"`

	// CreatedAfter Filter alias — only entries created after this value.
	CreatedAfter *openapi_types.Date `json:"created_after,omitempty"`

	// CreatedAt Date on which the time entry was created.
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// CreatedBefore Filter alias — only entries created before this value.
	CreatedBefore *openapi_types.Date `json:"created_before,omitempty"`

	// Creator The person who created this time entry.
	Creator *interface{} `json:"creator,omitempty"`

	// CreatorId creator id of the time entry.
	CreatorId *int `json:"creator_id,omitempty"`

	// Currency Currency code for financial values on this time entry.
	Currency *string `json:"currency,omitempty"`

	// CurrencyDefault Currency code in the organization's default currency.
	CurrencyDefault *interface{} `json:"currency_default,omitempty"`

	// CurrencyNormalized Currency code in the normalized reporting currency.
	CurrencyNormalized *interface{} `json:"currency_normalized,omitempty"`

	// Date Date for which the time was tracked.
	Date *openapi_types.Date `json:"date,omitempty"`

	// DealId ID of the deal/budget this time was tracked on.
	DealId *int `json:"deal_id,omitempty"`

	// DealName Name of the deal/budget this time was tracked on.
	DealName *interface{} `json:"deal_name,omitempty"`

	// DealSubsidiary The subsidiary of the budget/deal this time was tracked on.
	DealSubsidiary *interface{} `json:"deal_subsidiary,omitempty"`

	// DealSubsidiaryId ID of the subsidiary of the deal.
	DealSubsidiaryId *int `json:"deal_subsidiary_id,omitempty"`

	// DesignatedApproverId Filter time entries to those whose budget has the specified designated approver.
	DesignatedApproverId *int `json:"designated_approver_id,omitempty"`

	// EndedAt Computed end timestamp (started_at + time minutes).
	EndedAt *openapi_types.Date `json:"ended_at,omitempty"`

	// FacilityOverheadCost Facility overhead portion of the cost.
	FacilityOverheadCost *interface{} `json:"facility_overhead_cost,omitempty"`

	// FacilityOverheadCostDefault Facility overhead cost in the organization's default currency.
	FacilityOverheadCostDefault *interface{} `json:"facility_overhead_cost_default,omitempty"`

	// FacilityOverheadCostNormalized Facility overhead cost in the normalized reporting currency.
	FacilityOverheadCostNormalized *interface{} `json:"facility_overhead_cost_normalized,omitempty"`

	// Id Unique identifier of the time entry.
	Id *int `json:"id,omitempty"`

	// IntercompanyHours True when the person's subsidiary differs from the deal subsidiary.
	IntercompanyHours *bool `json:"intercompany_hours,omitempty"`

	// InternalOverheadCost Internal overhead portion of the cost.
	InternalOverheadCost *interface{} `json:"internal_overhead_cost,omitempty"`

	// InternalOverheadCostDefault Internal overhead cost in the organization's default currency.
	InternalOverheadCostDefault *interface{} `json:"internal_overhead_cost_default,omitempty"`

	// InternalOverheadCostNormalized Internal overhead cost in the normalized reporting currency.
	InternalOverheadCostNormalized *interface{} `json:"internal_overhead_cost_normalized,omitempty"`

	// InvoiceAttribution The invoice attribution linking this entry to an invoice.
	InvoiceAttribution *interface{} `json:"invoice_attribution,omitempty"`

	// InvoiceAttributionId ID of the invoice attribution linking this entry to an invoice.
	InvoiceAttributionId *int `json:"invoice_attribution_id,omitempty"`

	// InvoiceId ID of the invoice associated via attribution.
	InvoiceId *int `json:"invoice_id,omitempty"`

	// Invoiced Whether this time entry has been invoiced to the client.
	Invoiced *bool `json:"invoiced,omitempty"`

	// InvoicingStatus Current invoicing status of the time entry.
	InvoicingStatus *ResourceTimeEntryInvoicingStatus `json:"invoicing_status,omitempty"`

	// JiraIssueId Jira Issue ID if tracked from a Jira integration.
	JiraIssueId *string `json:"jira_issue_id,omitempty"`

	// JiraIssueStatus Current status of the linked Jira issue.
	JiraIssueStatus *string `json:"jira_issue_status,omitempty"`

	// JiraIssueSummary Summary text of the linked Jira issue.
	JiraIssueSummary *string `json:"jira_issue_summary,omitempty"`

	// JiraOrganization Jira organization name for the linked issue.
	JiraOrganization *string `json:"jira_organization,omitempty"`

	// JiraWorklogId Jira Worklog ID for synced entries.
	JiraWorklogId *string `json:"jira_worklog_id,omitempty"`

	// LastActivityAt Date when the last change was made (edit, approval, move, etc.).
	LastActivityAt *time.Time `json:"last_activity_at,omitempty"`

	// LastActor The last person who made changes to this entry.
	LastActor *interface{} `json:"last_actor,omitempty"`

	// LastActorId last actor id of the time entry.
	LastActorId *int `json:"last_actor_id,omitempty"`

	// Note Description of what the person was working on.
	Note *string `json:"note,omitempty"`

	// Organization The organization this time entry belongs to.
	Organization *interface{} `json:"organization,omitempty"`

	// Overhead Whether this time entry is included in overhead calculations.
	Overhead *bool `json:"overhead,omitempty"`

	// OverheadCost Total overhead cost (internal + facility) of tracked time.
	OverheadCost *interface{} `json:"overhead_cost,omitempty"`

	// OverheadCostDefault Total overhead cost in the organization's default currency.
	OverheadCostDefault *interface{} `json:"overhead_cost_default,omitempty"`

	// OverheadCostNormalized Total overhead cost in the normalized reporting currency.
	OverheadCostNormalized *interface{} `json:"overhead_cost_normalized,omitempty"`

	// ParentCompanyId Filter time entries by the parent company of the client linked to their budget.
	ParentCompanyId *int `json:"parent_company_id,omitempty"`

	// PeopleCustomFields Custom field values for the person who tracked time.
	PeopleCustomFields *string `json:"people_custom_fields,omitempty"`

	// Person The person who tracked this time.
	Person *interface{} `json:"person,omitempty"`

	// PersonId ID of the person who tracked time.
	PersonId *int `json:"person_id,omitempty"`

	// PersonName Name of the person who tracked time.
	PersonName *interface{} `json:"person_name,omitempty"`

	// PersonSubsidiary The subsidiary of the person who tracked time.
	PersonSubsidiary *interface{} `json:"person_subsidiary,omitempty"`

	// PersonSubsidiaryId ID of the subsidiary of the person who tracked time.
	PersonSubsidiaryId *int `json:"person_subsidiary_id,omitempty"`

	// PersonTags Tags of the person who tracked time.
	PersonTags *string `json:"person_tags,omitempty"`

	// ProjectId ID of the project associated with the service.
	ProjectId *int `json:"project_id,omitempty"`

	// ProjectManagerId ID of the project manager.
	ProjectManagerId *int `json:"project_manager_id,omitempty"`

	// ProjectTypeId Project type ID.
	ProjectTypeId *int `json:"project_type_id,omitempty"`

	// Query Full-text search query across time entry fields.
	Query *string `json:"query,omitempty"`

	// RecognizedTime Recognized time used in budget spending and accrual-based revenue calculations.
	RecognizedTime *int `json:"recognized_time,omitempty"`

	// Rejected Whether this time entry was rejected during approval.
	Rejected *interface{} `json:"rejected,omitempty"`

	// RejectedAt Timestamp when the time entry was rejected.
	RejectedAt *time.Time `json:"rejected_at,omitempty"`

	// RejectedReason Reason provided when the time entry was rejected.
	RejectedReason *string `json:"rejected_reason,omitempty"`

	// Rejecter The person who rejected this time entry.
	Rejecter *interface{} `json:"rejecter,omitempty"`

	// ResponsibleId ID of the responsible person.
	ResponsibleId *int `json:"responsible_id,omitempty"`

	// RoleId Role ID of the person who tracked time.
	RoleId *int `json:"role_id,omitempty"`

	// SectionName Name of the section the service belongs to.
	SectionName *string `json:"section_name,omitempty"`

	// Service The budget service this time was tracked against.
	Service *interface{} `json:"service,omitempty"`

	// ServiceId ID of the service the time was tracked against.
	ServiceId *int `json:"service_id,omitempty"`

	// ServiceName Name of the service the time was tracked against.
	ServiceName *interface{} `json:"service_name,omitempty"`

	// ServiceTypeId Service type ID of the associated service.
	ServiceTypeId *int `json:"service_type_id,omitempty"`

	// StageType Stage type of the associated deal.
	StageType *ResourceTimeEntryStageType `json:"stage_type,omitempty"`

	// StartedAfter Filter alias — only entries started after this value.
	StartedAfter *openapi_types.Date `json:"started_after,omitempty"`

	// StartedAt Start date and time of the time entry.
	StartedAt *time.Time `json:"started_at,omitempty"`

	// StartedBefore Filter alias — only entries started before this value.
	StartedBefore *openapi_types.Date `json:"started_before,omitempty"`

	// Status Approval status of the time entry.
	Status *ResourceTimeEntryStatus `json:"status,omitempty"`

	// Submitted Whether this time entry has been submitted for approval via a timesheet.
	Submitted *interface{} `json:"submitted,omitempty"`

	// Task The task the person was working on.
	Task *interface{} `json:"task,omitempty"`

	// TaskId ID of the task the person was working on.
	TaskId *int `json:"task_id,omitempty"`

	// TaskListId ID of the task list the task belongs to.
	TaskListId *int `json:"task_list_id,omitempty"`

	// Time Duration of work in minutes.
	Time *int `json:"time,omitempty"`

	// TimerStartedAt When the timer was started (if tracked via timer).
	TimerStartedAt *time.Time `json:"timer_started_at,omitempty"`

	// TimerStoppedAt When the timer was stopped.
	TimerStoppedAt *time.Time `json:"timer_stopped_at,omitempty"`

	// Timesheet The daily timesheet this entry belongs to (unit of approval submission).
	Timesheet *interface{} `json:"timesheet,omitempty"`

	// TrackMethodId How the time was recorded: manually, via timer, or mixed.
	TrackMethodId *ResourceTimeEntryTrackMethodId `json:"track_method_id,omitempty"`

	// UnitId Tracking unit ID of the associated service.
	UnitId *ResourceTimeEntryUnitId `json:"unit_id,omitempty"`

	// UpdatedAt Timestamp of last modification.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`

	// Updater The person who last updated this time entry.
	Updater *interface{} `json:"updater,omitempty"`

	// UseSalaryCurrency Whether to compute costs using the person's salary currency instead of the deal currency.
	UseSalaryCurrency *bool `json:"use_salary_currency,omitempty"`

	// WorkCost Labor cost based on the person's salary rate.
	WorkCost *interface{} `json:"work_cost,omitempty"`

	// WorkCostDefault Labor cost in the organization's default currency.
	WorkCostDefault *interface{} `json:"work_cost_default,omitempty"`

	// WorkCostNormalized Labor cost in the normalized reporting currency.
	WorkCostNormalized *interface{} `json:"work_cost_normalized,omitempty"`
}

// ResourceTimeEntryBillingTypeId Billing type of the associated service.
type ResourceTimeEntryBillingTypeId int

// ResourceTimeEntryInvoicingStatus Current invoicing status of the time entry.
type ResourceTimeEntryInvoicingStatus int

// ResourceTimeEntryStageType Stage type of the associated deal.
type ResourceTimeEntryStageType int

// ResourceTimeEntryStatus Approval status of the time entry.
type ResourceTimeEntryStatus int

// ResourceTimeEntryTrackMethodId How the time was recorded: manually, via timer, or mixed.
type ResourceTimeEntryTrackMethodId int

// ResourceTimeEntryUnitId Tracking unit ID of the associated service.
type ResourceTimeEntryUnitId int
